[package]
name = "map_generation"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
rand = "0.8.5"
rand_chacha = "0.3.1"
rayon = "1.10.0"

[[bin]]
name = "generate_map"
path = "src/main.rs"

[lib]
name = "map_generation"
path = "src/lib.rs"
